/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\xgentTheme.ts
 * Command: astryx theme build src\theme\xgentTheme.ts --out src\theme\xgentTheme.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/// <reference path="./xgent-chat.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const xgentChatTheme: DefinedTheme;
