/** Shared state/action vocabulary, independent of any renderer or component library. */
export const presentationActionContracts = {
  VStack: { events: [] },
  HStack: { events: [] },
  ScrollView: { events: [] },
  Card: { events: [] },
  Section: { events: [] },
  Text: { events: [] },
  Heading: { events: [] },
  Button: { events: ["press"] },
  TextInput: { events: ["changeText", "commitText"] },
  ShortcutRecorder: { events: ["recordShortcut"] },
  NumberInput: { events: ["changeNumber"] },
  ColorInput: { events: ["changeColor"] },
  TimeInput: { events: ["changeText"] },
  TextArea: { events: ["changeText"] },
  Switch: { events: ["changeBoolean"] },
  Selector: { events: ["changeSelection"] },
  SegmentedControl: { events: ["changeSelection"] },
  Menu: { events: ["press"] },
  Divider: { events: [] },
  Progress: { events: [] },
  ProgressBar: { events: [] },
  Badge: { events: [] },
  Banner: { events: [] },
  EmptyState: { events: [] },
  StatusDot: { events: [] },
  Slider: { events: ["changeNumber"] },
  Collapsible: { events: [] },
  Markdown: { events: ["highlightCode", "renderDiagram"] },
  CodeBlock: { events: ["highlightCode"] },
  List: { events: [] },
  ProviderList: { events: ["reorderProviders"] },
  TreeRow: { events: ["press"] },
  SettingsGroup: { events: [] },
  SettingsLayout: { events: [] },
  NavigationRow: { events: ["press"] },
  IconButton: { events: ["press"] },
  Spacer: { events: [] },
  Composer: { events: [] },
  ComposerInput: { events: ["changeText"] },
  ChatLayout: { events: [] },
  ChatMessage: { events: [] },
  Thinking: { events: [] },
  ToolCall: { events: [] },
  ActivityPreview: { events: ["press"] },
  TaskProgress: { events: [] },
  TaskStep: { events: [] },
  BrowserViewport: { events: ["reportViewport"] },
  BrowserLayout: { events: [] },
  MediaPreview: { events: [] },
  SpreadsheetGrid: { events: ["changeCell"] },
  HTMLPreview: { events: [] },
  FilePicker: { events: ["pickFiles"] },
  TerminalLayout: { events: [] },
  TerminalViewport: { events: ["streamTerminal"] },
  TerminalToolbar: { events: [] },
} as const;

export type PresentationKind = keyof typeof presentationActionContracts;

export const presentationNodeProperties = [
  "label",
  "text",
  "value",
  "action",
  "commitAction",
  "diagramAction",
  "focusRequest",
  "disabled",
  "destructive",
  "prominent",
  "secure",
  "secondary",
  "spacing",
  "padding",
  "indent",
  "fill",
  "alignment",
  "width",
  "minWidth",
  "maxWidth",
  "height",
  "minHeight",
  "maxHeight",
  "maxLines",
  "wrap",
  "variant",
  "size",
  "icon",
  "selected",
  "role",
  "status",
  "language",
  "minimum",
  "maximum",
  "step",
  "integerOnly",
  "clearable",
  "current",
  "total",
  "options",
  "accessibilityLabel",
  "accessibilityHint",
  "accessibilityValue",
  "children",
] as const;
