// Generated by scripts/generate-native-ui.mjs from presentation/astryx-swiftui.json.
// Edit the mapping, not this file.
export const presentationTokenMappings = {
  "--color-accent": {
    target: "palette.accent",
    type: "color",
    fallback: ["#0088ff", "#0a84ff"],
  },
  "--color-text-accent": {
    target: "palette.accentText",
    type: "color",
    fallback: ["#006edc", "#6eb4ff"],
  },
  "--color-background-body": {
    target: "palette.background",
    type: "color",
    fallback: ["#f5f5f7", "#171717"],
  },
  "--color-background-surface": {
    target: "palette.surface",
    type: "color",
    fallback: ["#ffffff", "#212121"],
  },
  "--color-background-card": {
    target: "palette.card",
    type: "color",
    fallback: ["#ffffff", "#2a2a2a"],
  },
  "--color-background-popover": {
    target: "palette.popover",
    type: "color",
    fallback: ["#ffffff", "#2a2a2a"],
  },
  "--color-background-muted": {
    target: "palette.muted",
    type: "color",
    fallback: ["#eeeeef", "#303030"],
  },
  "--color-text-primary": {
    target: "palette.text",
    type: "color",
    fallback: ["#0d0d0d", "#ececec"],
  },
  "--color-text-secondary": {
    target: "palette.secondaryText",
    type: "color",
    fallback: ["#6e6e73", "#b4b4b4"],
  },
  "--color-text-disabled": {
    target: "palette.disabledText",
    type: "color",
    fallback: ["#8e8e93", "#7c7c80"],
  },
  "--color-border": {
    target: "palette.border",
    type: "color",
    fallback: ["#0000001a", "#ffffff1f"],
  },
  "--color-border-emphasized": {
    target: "palette.emphasizedBorder",
    type: "color",
    fallback: ["#d9d9d9", "#4a4a4a"],
  },
  "--color-shadow": {
    target: "palette.shadow",
    type: "color",
    fallback: ["#000000", "#000000"],
  },
  "--radius-inner": {
    target: "radius.inner",
    type: "length",
    fallback: [8, 8],
  },
  "--radius-element": {
    target: "radius.element",
    type: "length",
    fallback: [14, 14],
  },
  "--radius-container": {
    target: "radius.container",
    type: "length",
    fallback: [26, 26],
  },
  "--radius-page": {
    target: "radius.overlay",
    type: "length",
    fallback: [32, 32],
  },
  "--radius-chat": {
    target: "radius.chat",
    type: "length",
    fallback: [28, 28],
  },
  "--spacing-1": {
    target: "spacing.xs",
    type: "length",
    fallback: [4, 4],
  },
  "--spacing-2": {
    target: "spacing.sm",
    type: "length",
    fallback: [8, 8],
  },
  "--spacing-3": {
    target: "spacing.md",
    type: "length",
    fallback: [12, 12],
  },
  "--spacing-4": {
    target: "spacing.lg",
    type: "length",
    fallback: [16, 16],
  },
  "--spacing-6": {
    target: "spacing.xl",
    type: "length",
    fallback: [24, 24],
  },
  "--size-element-sm": {
    target: "control.small",
    type: "length",
    fallback: [32, 32],
  },
  "--size-element-md": {
    target: "control.medium",
    type: "length",
    fallback: [40, 40],
  },
  "--size-element-lg": {
    target: "control.large",
    type: "length",
    fallback: [44, 44],
  },
  "--font-size-xs": {
    target: "typography.caption",
    type: "length",
    fallback: [12, 12],
  },
  "--font-size-sm": {
    target: "typography.supporting",
    type: "length",
    fallback: [13, 13],
  },
  "--font-size-base": {
    target: "typography.body",
    type: "length",
    fallback: [15, 15],
  },
  "--duration-fast": {
    target: "motion.fast",
    type: "duration",
    fallback: [120, 120],
  },
  "--duration-medium": {
    target: "motion.medium",
    type: "duration",
    fallback: [240, 240],
  },
  "--duration-slow": {
    target: "motion.slow",
    type: "duration",
    fallback: [650, 650],
  },
  "--ease-standard": {
    target: "motion.curve",
    type: "timingFunction",
    fallback: ["cubic-bezier(0.2, 0, 0, 1)", "cubic-bezier(0.2, 0, 0, 1)"],
  },
  "--astryx-theme-xgent-glass-material-surface-opacity": {
    target: "material.surfaceOpacity",
    type: "percentage",
    fallback: [0.8, 0.72],
  },
  "--astryx-theme-xgent-glass-material-popover-opacity": {
    target: "material.popoverOpacity",
    type: "percentage",
    fallback: [0.88, 0.8],
  },
  "--astryx-theme-xgent-glass-material-blur": {
    target: "material.blur",
    type: "length",
    fallback: [28, 28],
  },
  "--astryx-theme-xgent-glass-material-saturation": {
    target: "material.saturation",
    type: "percentage",
    fallback: [1.45, 1.45],
  },
  "--astryx-theme-xgent-glass-material-shadow-opacity": {
    target: "material.shadowOpacity",
    type: "number",
    fallback: [0.1, 0.34],
  },
} as const;

export type PresentationTokenName = keyof typeof presentationTokenMappings;
