package com.ohi.xagent.mobileexecution

import android.system.Os
import java.io.File

internal object RootfsEnvironment {
    fun prepare(rootfs: File, alpineBranch: String? = null) {
        val etc = File(rootfs, "etc").apply { mkdirs() }
        if (alpineBranch != null) {
            require(ALPINE_BRANCH.matches(alpineBranch)) { "invalid Alpine repository branch" }
            File(etc, "apk").mkdirs()
            File(etc, "apk/repositories").writeText(
                "${ALPINE_REPOSITORY}/$alpineBranch/main\n" +
                    "${ALPINE_REPOSITORY}/$alpineBranch/community\n",
            )
        }
        File(etc, "resolv.conf").writeText(
            """# Generated by XAgent mobile execution.
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 223.5.5.5
options edns0
""",
        )
        File(etc, "hosts").apply {
            if (!isFile || !readText().contains("127.0.0.1")) {
                writeText("127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n")
            }
        }
        File(etc, "hostname").apply {
            if (!isFile || readText().isBlank()) writeText("xagent-mobile\n")
        }
        listOf("root", "tmp", "var/tmp").forEach { relative ->
            File(rootfs, relative).mkdirs()
        }
        // 01777: world-writable with sticky bit, matching a normal Linux rootfs.
        runCatching { Os.chmod(File(rootfs, "tmp").absolutePath, 1023) }
        runCatching { Os.chmod(File(rootfs, "var/tmp").absolutePath, 1023) }
    }

    private const val ALPINE_REPOSITORY = "https://dl-cdn.alpinelinux.org/alpine"
    private val ALPINE_BRANCH = Regex("v[0-9]+\\.[0-9]+")
}
