allowBuilds:
  '@astryxdesign/cli': true
  '@astryxdesign/core': true
  '@google/genai': true
  esbuild: true
  protobufjs: true
patchedDependencies:
  '@astryxdesign/core@0.6.0': patches/@astryxdesign__core@0.6.0.patch
