package com.ohi.xgent.mobileexecution

import android.content.Context
import android.net.ConnectivityManager
import android.system.Os
import java.io.File

internal object RootfsEnvironment {
    fun prepare(rootfs: File, context: Context, alpineBranch: String? = null) {
        val etc = File(rootfs, "etc").apply { mkdirs() }
        if (alpineBranch != null) {
            require(ALPINE_BRANCH.matches(alpineBranch)) { "invalid Alpine repository branch" }
            File(etc, "apk").mkdirs()
            File(etc, "apk/repositories").writeText(
                "${ALPINE_REPOSITORY}/$alpineBranch/main\n" +
                    "${ALPINE_REPOSITORY}/$alpineBranch/community\n",
            )
        }
        File(etc, "resolv.conf").writeText(resolverConfig(context))
        File(etc, "hosts").apply {
            if (!isFile || !readText().contains("127.0.0.1")) {
                writeText("127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n")
            }
        }
        File(etc, "hostname").apply {
            if (!isFile || readText().isBlank()) writeText("xgent-mobile\n")
        }
        listOf("root", "tmp", "var/tmp").forEach { relative ->
            File(rootfs, relative).mkdirs()
        }
        // 01777: world-writable with sticky bit, matching a normal Linux rootfs.
        runCatching { Os.chmod(File(rootfs, "tmp").absolutePath, 1023) }
        runCatching { Os.chmod(File(rootfs, "var/tmp").absolutePath, 1023) }
    }

    private fun resolverConfig(context: Context): String {
        val link = runCatching {
            val manager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager
            val network = manager?.activeNetwork
            if (manager != null && network != null) manager.getLinkProperties(network) else null
        }.getOrNull()
        val servers = link?.dnsServers?.mapNotNull { it.hostAddress }?.distinct().orEmpty()
        val domains = link?.domains.orEmpty().split(Regex("[,\\s]+"))
            .filter { it.isNotBlank() && it.matches(Regex("[A-Za-z0-9._-]+")) }
            .take(6)
        return buildString {
            append("# Generated by Xgent mobile execution.\n")
            if (domains.isNotEmpty()) append("search ${domains.joinToString(" ")}\n")
            for (server in servers.ifEmpty { listOf("1.1.1.1", "8.8.8.8") }) {
                append("nameserver $server\n")
            }
            append("options edns0\n")
        }
    }

    fun proxyEnvironment(context: Context): List<String> {
        val proxy = runCatching {
            val manager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager
            manager?.defaultProxy
        }.getOrNull()
        val host = proxy?.host?.trim().orEmpty()
        val port = proxy?.port ?: 0
        if (host.isEmpty() || port !in 1..65535) return emptyList()
        val urlHost = if (host.contains(':') && !host.startsWith('[')) "[$host]" else host
        val url = "http://$urlHost:$port"
        return listOf(
            "http_proxy=$url",
            "https_proxy=$url",
            "HTTP_PROXY=$url",
            "HTTPS_PROXY=$url",
            "no_proxy=localhost,127.0.0.1,::1",
            "NO_PROXY=localhost,127.0.0.1,::1",
        )
    }

    private const val ALPINE_REPOSITORY = "https://dl-cdn.alpinelinux.org/alpine"
    private val ALPINE_BRANCH = Regex("v[0-9]+\\.[0-9]+")
}
