// Generated by scripts/generate-native-ui.mjs from presentation/astryx-swiftui.json.
// Edit the mapping, not this file.
import SwiftUI

enum XgentNodeKind: String, Decodable {
    case vStack = "VStack"
    case hStack = "HStack"
    case scrollView = "ScrollView"
    case card = "Card"
    case section = "Section"
    case text = "Text"
    case heading = "Heading"
    case button = "Button"
    case textInput = "TextInput"
    case textArea = "TextArea"
    case toggle = "Switch"
    case selector = "Selector"
    case segmentedControl = "SegmentedControl"
    case menu = "Menu"
    case divider = "Divider"
    case progress = "Progress"
}

extension XgentNodeView {
    @ViewBuilder var generatedContent: some View {
        switch node.kind {
        case .vStack:
            VStack(alignment: .leading, spacing: node.spacing.map { CGFloat($0) }) { children }
        case .hStack:
            HStack(spacing: node.spacing.map { CGFloat($0) }) { children }
        case .scrollView:
            ScrollView { LazyVStack(alignment: .leading, spacing: 12) { children } }
        case .card:
            VStack(alignment: .leading, spacing: 12) { children }
                .padding(16).modifier(XgentGlassSurface())
        case .section:
            GroupBox { VStack(alignment: .leading, spacing: 12) { children } } label: {
                Text(node.label ?? "")
            }
        case .text:
            Text(node.text ?? "")
                .foregroundStyle(node.secondary == true ? .secondary : .primary)
                .textSelection(.enabled)
                .fixedSize(horizontal: false, vertical: true)
        case .heading:
            Text(node.text ?? "").font(.headline).accessibilityAddTraits(.isHeader)
        case .button:
            nativeButton
        case .textInput:
            VStack(alignment: .leading, spacing: 4) {
                if let label = node.label, !label.isEmpty { Text(label).font(.subheadline) }
                if node.secure == true {
                    SecureField(node.text ?? "", text: textBinding)
                        .textFieldStyle(.roundedBorder)
                        .accessibilityLabel(node.label ?? node.text ?? "")
                } else {
                    TextField(node.text ?? "", text: textBinding)
                        .textFieldStyle(.roundedBorder)
                        .accessibilityLabel(node.label ?? node.text ?? "")
                }
            }
        case .textArea:
            VStack(alignment: .leading, spacing: 4) {
                if let label = node.label, !label.isEmpty { Text(label).font(.subheadline) }
                TextEditor(text: textBinding).frame(minHeight: 100)
                    .accessibilityLabel(node.label ?? node.text ?? "")
            }
        case .toggle:
            Toggle(node.label ?? "", isOn: boolBinding)
        case .selector:
            picker.pickerStyle(.menu)
        case .segmentedControl:
            picker.pickerStyle(.segmented)
        case .menu:
            Menu { children } label: { Text(node.label ?? "") }
        case .divider:
            Divider()
        case .progress:
            ProgressView(node.label ?? "")
        }
    }
}
