import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { checkNativeContracts, validateNativeContracts } from "../../../../scripts/check-native-ui.mjs";

const nativeViewSource = readFileSync(new URL("../../src-tauri/apple/PresentationView.swift", import.meta.url), "utf8");
const nativeLayoutSource = readFileSync(new URL("../../src-tauri/apple/PresentationLayout.swift", import.meta.url), "utf8");
const nativeMobileSource = readFileSync(new URL("../../src-tauri/apple/PresentationMobile.swift", import.meta.url), "utf8");
const nativeMobileNodeSource = readFileSync(new URL("../../src-tauri/apple/PresentationMobileNode.swift", import.meta.url), "utf8");
const nativeDesktopSource = readFileSync(new URL("../../src-tauri/apple/PresentationDesktopContent.swift", import.meta.url), "utf8");
const nativeSettingsSource = readFileSync(new URL("../../src-tauri/apple/PresentationDesktopSettings.swift", import.meta.url), "utf8");
const nativeMobileSettingsSource = readFileSync(new URL("../../src-tauri/apple/PresentationMobileSettings.swift", import.meta.url), "utf8");
const nativeWindowSource = readFileSync(new URL("../../src-tauri/apple/PresentationWindowChrome.swift", import.meta.url), "utf8");
const nativeHostSource = readFileSync(new URL("../../src-tauri/apple/PresentationHost.swift", import.meta.url), "utf8");
const nativePanelSource = readFileSync(new URL("../../src-tauri/apple/PresentationWorkspacePanel.swift", import.meta.url), "utf8");

function contracts() {
  const read = path => readFileSync(new URL(path, import.meta.url), "utf8");
  return {
    protocol: read("../../src/presentation/protocol.ts"),
    swiftProtocol: read("../../src-tauri/apple/PresentationProtocol.swift"),
    types: read("../../src/presentation/types.ts"),
    model: read("../../src-tauri/apple/PresentationModel.swift"),
  };
}

test("handwritten native UI shares a checked state/action schema without an Astryx generator", () => {
  const result = checkNativeContracts();
  assert.ok(result.kinds > 40);
  assert.equal(result.properties, 46);
  for (const source of [nativeViewSource, nativeDesktopSource, nativeMobileSource, nativeMobileNodeSource]) {
    assert.doesNotMatch(source, /generatedContent|Generated by/);
  }
});

test("state contract checks reject a missing kind or a field mismatch without generating UI", () => {
  const sources = contracts();
  assert.throws(() => validateNativeContracts({ ...sources, swiftProtocol: sources.swiftProtocol.replace('    case button = "Button"', '') }), /kinds/);
  assert.throws(() => validateNativeContracts({ ...sources, types: sources.types.replace('  focusRequest?: number;', '') }), /properties/);
  assert.throws(() => validateNativeContracts({ ...sources, model: sources.model.replace('    let action: String?', '') }), /properties/);
  assert.throws(() => validateNativeContracts({ ...sources, swiftProtocol: sources.swiftProtocol.replace('["changeText"]', '["changeNumber"]') }), /events/);
});

test("macOS window toolbar reserves native content space and shares the sidebar state with its panes", () => {
  assert.match(nativeWindowSource, /NSToolbarDelegate/);
  assert.match(nativeWindowSource, /window\.toolbarStyle = \.unified/);
  assert.match(nativeWindowSource, /window\.toolbar = originalToolbar/);
  assert.match(nativeHostSource, /container\.safeAreaLayoutGuide\.topAnchor/);
  assert.match(nativeHostSource, /windowChrome\.install\(on: window\)/);
  assert.match(nativeHostSource, /windowChrome\.detach\(\)/);
  assert.match(nativePanelSource, /model\.workspaceState\.visible/);
  assert.doesNotMatch(nativePanelSource, /@State private var state = XgentWorkspacePanelState/);
  assert.match(nativeLayoutSource, /!model\.windowChromeInstalled \|\| \$0\.id != "toolbar"/);
  assert.doesNotMatch(nativeWindowSource, /WKWebView|evaluateJavaScript|startDragging/);
});

test("macOS narrow sidebar uses an accessible drawer without forcing both pane minimums", () => {
  assert.match(nativeLayoutSource, /XgentDesktopSidebarPlacement\(/);
  assert.match(nativeLayoutSource, /\.disabled\(drawerVisible\)/);
  assert.match(nativeLayoutSource, /\.allowsHitTesting\(!drawerVisible\)/);
  assert.match(nativeLayoutSource, /\.accessibilityHidden\(drawerVisible\)/);
  assert.match(nativeLayoutSource, /xgent-sidebar-dismiss-backdrop/);
  assert.match(nativeLayoutSource, /placement\.widthToRemember\(width\)/);
  assert.match(nativeLayoutSource, /onChange\(of: root\?\.node\(id: "chat"\)\?\.value\)/);
});

test("native glass keeps grouped surfaces distinct from floating controls", () => {
  assert.match(nativeViewSource, /var floating: Bool/);
  assert.match(
    nativeViewSource,
    /floating \? material\.popoverOpacity : material\.surfaceOpacity/,
  );
  assert.match(nativeDesktopSource, /XgentActionButton\(node: node, document: document, model: model\)/);
  for (const modifier of ["Insets", "FixedFrame", "BoundsFrame", "TextLayout", "Control"]) {
    assert.match(nativeViewSource, new RegExp(`struct XgentNode${modifier}Modifier: ViewModifier`));
  }
  assert.match(
    nativeViewSource,
    /AnyView\(desktopContent\)[\s\S]*?\.modifier\(XgentNodeFixedFrameModifier\([\s\S]*?\.modifier\(XgentNodeBoundsFrameModifier\(/,
  );
  assert.match(
    nativeLayoutSource,
    /XgentGlassSurface\(radius: CGFloat\(presentationTheme\.radius\.chat\), floating: true\)/,
  );
  assert.match(nativeLayoutSource, /child\.icon == nil \? 0 : 36/);
  assert.match(nativeDesktopSource, /XgentSelector\(node: node, document: document, model: model\)/);
  assert.match(nativeViewSource, /Form \{[\s\S]*?\.formStyle\(\.grouped\)/);
  assert.doesNotMatch(nativeViewSource, /\.presentationBackground\(/);
  assert.match(nativeLayoutSource, /List\(node\.children \?\? \[\]\)/);
  assert.match(nativeLayoutSource, /document\.formFactor == \.mobile[\s\S]*?\.listStyle\(\.insetGrouped\)/);
  assert.match(nativeLayoutSource, /\.listStyle\(\.sidebar\)/);
  assert.match(nativeSettingsSource, /struct XgentDesktopSettingsLayout: View/);
  assert.match(nativeSettingsSource, /geometry\.size\.width >= 760/);
  assert.doesNotMatch(nativeSettingsSource, /minWidth: 900|NavigationSplitView/);
  assert.match(nativeLayoutSource, /HSplitView \{/);
  assert.match(nativeLayoutSource, /@AppStorage\("xgent\.native\.sidebar-width\.v1"\)/);
});

test("the complete iOS application surface is handwritten and bypasses generated mappings", () => {
  assert.match(nativeMobileSource, /struct XgentIOSRootPresentation: View/);
  assert.match(nativeMobileSource, /struct XgentIOSWorkspacePresentation: View/);
  assert.match(nativeMobileSource, /struct XgentIOSPagePresentation: View/);
  assert.match(nativeMobileSource, /struct XgentIOSSheetPresentation: View/);
  const chatSource = nativeMobileSource.slice(
    nativeMobileSource.indexOf("private struct XgentIOSChatPresentation"),
    nativeMobileSource.indexOf("private struct XgentIOSTranscript"),
  );
  assert.doesNotMatch(chatSource, /\.safeAreaInset\(edge: \.bottom/);
  assert.match(nativeMobileSource, /\.safeAreaInset\(edge: \.bottom, spacing: 0\)[\s\S]*?XgentProviderEditorFooter/);
  assert.match(nativeMobileSource, /if !isObscured, let composer \{\s*XgentIOSComposer\(node: composer/);
  assert.doesNotMatch(nativeMobileSource, /NavigationStack \{/);
  assert.doesNotMatch(nativeMobileSource, /@ToolbarContentBuilder/);
  assert.doesNotMatch(nativeMobileSource, /ToolbarItem\(placement:/);
  assert.match(nativeMobileSource, /\.frame\(minHeight: 68\)/);
  assert.match(nativeMobileSource, /geometry\.size\.width \* 0\.85/);
  const sidebarSource = nativeMobileSource.slice(
    nativeMobileSource.indexOf("private struct XgentIOSSidebarPresentation"),
    nativeMobileSource.indexOf("private struct XgentIOSSidebarFooter"),
  );
  assert.doesNotMatch(sidebarSource, /\.safeAreaBar\(edge: \.bottom/);
  assert.match(nativeMobileSource, /\.onScrollGeometryChange\(for: Bool\.self\)/);
  assert.match(nativeMobileSource, /\.onScrollPhaseChange/);
  assert.match(nativeMobileSource, /if grouped \{\s*XgentIOSSettingsForm\(nodes: contentNodes/);
  assert.match(nativeMobileSettingsSource, /ScrollView \{[\s\S]*?ForEach\(sections\)/);
  assert.match(nativeMobileSettingsSource, /XgentIOSSettingsCard\(section: section/);
  assert.match(nativeMobileNodeSource, /XgentSelector\(node: node, document: document, model: model\)/);
  assert.match(
    nativeMobileSource,
    /list == nil \? \[\.large\] : \[\.fraction\(0\.62\), \.large\][\s\S]*?\.presentationDetents\(detents\)/,
  );
  assert.match(nativeMobileSource, /\.presentationDragIndicator\(\.hidden\)/);
  assert.doesNotMatch(nativeMobileSource, /Capsule\(\)[\s\S]*?\.frame\(width: 40, height: 4\)/);
  assert.doesNotMatch(nativeMobileSource, /WebView|WKWebView|UIViewRepresentable/);
  assert.match(nativeMobileNodeSource, /struct XgentIOSNode: View/);
  assert.match(nativeMobileNodeSource, /switch node\.kind/);
  assert.match(nativeMobileNodeSource, /case \.composerInput:/);
  assert.match(nativeMobileNodeSource, /case \.settingsGroup:/);
  assert.match(nativeMobileNodeSource, /case \.browserViewport:/);
  assert.match(nativeMobileNodeSource, /XgentAttachmentPicker/);
  assert.match(nativeMobileNodeSource, /XgentNativeMenu\(node: node, document: document, model: model\)/);
  assert.match(nativeMobileNodeSource, /parentAxis != \.horizontal/);
  assert.match(nativeMobileNodeSource, /case \.list:[\s\S]*?XgentComposerSuggestions/);
  assert.match(nativeMobileNodeSource, /case \.settingsGroup:\s*settingsGroup/);
  assert.doesNotMatch(nativeMobileNodeSource, /\.map\(CGFloat\.init\)/);
  for (const source of [nativeMobileSource, nativeMobileNodeSource]) {
    assert.doesNotMatch(source, /XgentNodeView|XgentNodeChildren|generatedContent/);
  }
  assert.match(nativeViewSource, /#if os\(iOS\)\s*XgentIOSSheetPresentation/);
  assert.match(nativeMobileSource, /sheets\.firstIndex\(where: \{ \$0\.id == document\.id \}\)/);
  assert.match(nativeMobileSource, /return sheets\[index \+ 1\]/);
  assert.match(nativeMobileSource, /\.sheet\(item: Binding\(get: \{ nextSheet \}/);
  assert.match(nativeMobileSource, /model\.dismiss\(nextSheet\)/);
  assert.match(nativeMobileSource, /AnyView\(XgentIOSSheetPresentation\(initialDocument: next, model: model\)\)/);
  assert.match(nativeMobileSource, /XgentAlerts\(model: model, enabled: nextSheet == nil\)/);
  assert.match(nativeMobileSource, /XgentIOSChatPresentation\(document: document, model: model, isObscured: sidebar != nil\)/);
  assert.match(
    nativeLayoutSource,
    /root\.formFactor == \.mobile[\s\S]*?XgentIOSRootPresentation[\s\S]*?XgentIOSWorkspacePresentation/,
  );
  assert.match(nativeLayoutSource, /else \{\s*XgentIOSPagePresentation\(document: root, sidebar: sidebar/);
});
